export const projects = [
  {
    id: 1,
    title: "FirstMove",
    category: "Mobile / Full Stack",
    tags: ["React Native", "Node.js", "Real-time"],
    description:
      "A social platform that transforms events into private, interactive communities. Built mobile experiences with real-time engagement, intuitive discovery flows, and scalable user-driven features.",
    url: "https://firstmove.live/",
    year: "2025",
    featured: true,
    color: "#1a1a2e",
    accentColor: "#22c55e",
  },
  {
    id: 2,
    title: "COBRA (PENCOM)",
    category: "Full Stack",
    tags: ["Next.js", "NestJS", "TypeScript", "Government"],
    description:
      "A nationwide regulatory platform for pension administration in Nigeria. Built scalable frontend and backend systems using Next.js and NestJS, focusing on data validation, API reliability, and high-performance under heavy workloads.",
    url: "https://cobra.pencom.gov.ng/",
    year: "2025",
    featured: true,
    color: "#0f172a",
    accentColor: "#38bdf8",
  },

  {
    id: 3,
    title: "CapTable (Coronation Registrars)",
    category: "Frontend",
    tags: ["Angular", "TypeScript", "Finance"],
    description:
      "A financial modeling and shareholder management platform. Built complex dashboards, cap table modules, and responsive interfaces for managing equity and investor data.",
    url: "https://www.ctbycoronation.com/",
    year: "2024",
    featured: true,
    color: "#1e293b",
    accentColor: "#f59e0b",
  },
  {
    id: 4,
    title: "NearCash",
    category: "Full Stack",
    tags: ["React", "Node.js", "Fintech"],
    description:
      "A fintech platform enabling seamless digital payments and financial services. Contributed to frontend architecture and API integrations, focusing on performance and reliability.",
    url: "https://nearcash.cadencepay.us",
    year: "2024",
    featured: true,
    color: "#052e16",
    accentColor: "#4ade80",
  },
  {
    id: 5,
    title: "Culture Bridge",
    category: "Web App",
    tags: ["Next.js", "UI/UX", "Community"],
    description:
      "A platform designed to connect people across cultures through shared experiences and content. Focused on building a clean, engaging interface and smooth user interactions.",
    url: "https://culturebridge.ng/",
    year: "2024",
    featured: false,
    color: "#2a1a0e",
    accentColor: "#fb923c",
  },
  {
    id: 6,
    title: "Lifestores Healthcare",
    category: "Full Stack",
    tags: ["React", "Node.js", "Healthcare"],
    description: "A comprehensive healthcare platform connecting patients with pharmacies and health services across Nigeria.",
    url: "https://lifestoreshealthcare.com/",
    year: "2023",
    featured: true,
    color: "#1a2e1a",
    accentColor: "#4ade80",
  },

  {
    id: 7,
    title: "Asoebi Africa",
    category: "E-Commerce",
    tags: ["Next.js", "E-commerce", "Fashion"],
    description: "A premium African fashion e-commerce platform celebrating traditional fabric and modern design.",
    url: "https://staging.asoebi.africa/",
    year: "2023",
    featured: false,
    color: "#2a1a0e",
    accentColor: "#fb923c",
  },
  {
    id: 8,
    title: "Job Listing Platform",
    category: "Web App",
    tags: ["React", "CSS", "UX"],
    description: "A clean, performant job board with advanced filtering, real-time search, and company profiles.",
    url: "https://top-pro-neighboorhood.netlify.app/",
    year: "2022",
    featured: false,
    color: "#0e1a2a",
    accentColor: "#60a5fa",
  },
  {
    id: 9,
    title: "E-Commerce Illustration UI",
    category: "Web Design",
    tags: ["UI Design", "Illustration", "React"],
    description: "A visually rich e-commerce interface with custom illustrations, playful interactions, and a bold brand identity.",
    url: "https://competent-yalow-986023.netlify.app/",
    year: "2022",
    featured: false,
    color: "#1a0e2a",
    accentColor: "#c084fc",
  },
  {
    id: 10,
    title: "Neighborhood Services",
    category: "Full Stack",
    tags: ["React", "API", "Node.js"],
    description: "A hyper-local services marketplace connecting skilled professionals with customers in their area.",
    url: "https://top-pro-neighboorhood.netlify.app/",
    year: "2022",
    featured: false,
    color: "#1a1a0e",
    accentColor: "#facc15",
  },
  {
    id: 11,
    title: "LifeStore Healthcare Platform",
    category: "Full Stack",
    tags: ["React", "GraphQL", "Django", "Healthcare"],
    description:
      "Core healthcare platform connecting pharmacies, patients, and providers. Built scalable product features, user flows, and integrations with third-party services.",
    url: "https://lifestoreshealthcare.com/",
    year: "2023",
    featured: false,
    color: "#1a2e1a",
    accentColor: "#4ade80",
  },
  {
    id: 12,
    title: "LifeStore Pharmacy",
    category: "Web App",
    tags: ["React", "E-commerce", "Healthcare"],
    description:
      "An online pharmacy platform enabling users to browse and purchase medications. Focused on performance, usability, and seamless ordering experience.",
    url: "https://lifestorespharmacy.com/",
    year: "2023",
    featured: false,
    color: "#022c22",
    accentColor: "#34d399",
  },
  {
    id: 13,
    title: "LifeStore POS System",
    category: "Full Stack",
    tags: ["React", "Node.js", "Internal Tools"],
    description:
      "An internal point-of-sale system used by pharmacies for order processing and inventory management. Built for reliability, speed, and operational efficiency.",
    url: "https://pos.internal.ogapharmacy.com/",
    year: "2023",
    featured: false,
    color: "#1f2937",
    accentColor: "#60a5fa",
  },
];

export const skills = [
  { name: "React JS", level: 95 },
  { name: "Next.js", level: 90 },
  { name: "TypeScript", level: 85 },
  { name: "Node.js", level: 88 },
  { name: "Angular", level: 80 },
  { name: "React Native", level: 82 },
  { name: "NestJS", level: 78 },
  { name: "Django", level: 70 },
  { name: "PostgreSQL", level: 75 },
  { name: "AWS / GCP", level: 68 },
];

export const experience = [
  {
    period: "Mar 2021 – May 2021",
    title: "Back End Development & APIs",
    org: "FreeCodeCamp",
    description: "Built robust server-side applications and REST APIs, demonstrating proficiency in backend technologies.",
  },
  {
    period: "Jan 2021 – Mar 2021",
    title: "Data Structures & Algorithms",
    org: "FreeCodeCamp",
    description: "Acquired expertise in efficient algorithms, data structures, and algorithmic problem-solving.",
  },
  {
    period: "Nov 2020 – Feb 2021",
    title: "Front End Development Libraries",
    org: "FreeCodeCamp",
    description: "Mastered front-end libraries and responsive web design for delivering exceptional user experiences.",
  },
  {
    period: "Jul 2020",
    title: "Programming Foundations",
    org: "LinkedIn Learning",
    description: "Solidified foundational programming knowledge and core software development principles.",
  },
  {
    period: "Jul 2019 – Mar 2020",
    title: "Full Stack Web Development",
    org: "Little Drop Bootcamp",
    description: "Comprehensive frontend and backend bootcamp — built dynamic, responsive web applications end-to-end.",
  },
  {
    period: "2025 – 2027",
    title: "Master of Financial Engineering",
    org: "WorldQuant University",
    description: "Gained expertise in quantitative finance, algorithmic trading, and financial modeling — skills that enhance my analytical approach to software development.",
  },
  {
    period: "2014 – 2018",
    title: "B.Sc. Chemistry",
    org: "Obafemi Awolowo University",
    description: "Honed analytical thinking, precision, and complex problem-solving — skills that directly translate to software engineering.",
  },

];
